### ISSUE TITLE
Possible documentation error

### ISSUE THREAD

**Issue by sebastiandiel** [dankreider/musglyphs#1]
To achieve a 5-Lines-Repetition I need to input
`J :LLLL: K`
(notice the spaces and the different keys for first and final barline).
[Documentation ](https://github.com/dankreider/musglyphs/blob/main/MusGlyphs%20README.pdf)however suggests 
`KLLLLM`
I am working on a German (keyboard/locale setting etc.) Win10 machine with Libre Office Writer V6.2.6.2.

**Comment by dankreider** [comment]
Hi Sebastian, good catch. You're right, I need to adjust the font to add these back.
